name: 'Setup Repository'
description: 'Checkout code and setup Node.js environment'
inputs:
  cache:
    description: 'Cache type for dependencies'
    required: false
    default: 'npm'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Read .nvmrc
      id: nvmrc
      shell: bash
      run: |
        if [ -f .nvmrc ]; then
          echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        else
          echo "version=22.14.0" >> $GITHUB_OUTPUT
        fi
    
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '${{ steps.nvmrc.outputs.version }}'
        cache: '${{ inputs.cache }}'
    
    - name: Install dependencies
      shell: bash
      run: npm ci

